const TRANSLATIONS = {
  ar: {
    siteName: "الشركة المتحدة للتوابل",
    tagline: "جودة لا تُضاهى منذ عقود",
    searchPlaceholder: "ابحث عن منتج...",
    all: "الكل",
    addToCart: "أضف للسلة",
    cart: "السلة",
    cartEmpty: "السلة فارغة",
    total: "المجموع",
    sendWhatsapp: "إرسال الطلب عبر واتساب",
    currency: "IQD",
    remove: "حذف",
    noResults: "لا توجد نتائج",
    pieces: "قطعة",
    lang: "العربية",
    iqd: "د.ع",
  },
  ku: {
    siteName: "کۆمپانیای یەکگرتوو بۆ بهارات",
    tagline: "کوالێتی بێ‌وێنە لە دەیان ساڵ",
    searchPlaceholder: "بگەڕێ بۆ بەرهەم...",
    all: "هەمووی",
    addToCart: "زیادبکە بۆ سەبەت",
    cart: "سەبەت",
    cartEmpty: "سەبەت valaیە",
    total: "کۆی گشتی",
    sendWhatsapp: "ناردنی داواکاری لە ڕێگای واتساپ",
    currency: "IQD",
    remove: "سڕینەوە",
    noResults: "هیچ ئەنجامێک نەدۆزرایەوە",
    pieces: "دانە",
    lang: "کوردی",
    iqd: "د.ع",
  },
  en: {
    siteName: "United Spices Company",
    tagline: "Unmatched Quality for Decades",
    searchPlaceholder: "Search for a product...",
    all: "All",
    addToCart: "Add to Cart",
    cart: "Cart",
    cartEmpty: "Your cart is empty",
    total: "Total",
    sendWhatsapp: "Send Order via WhatsApp",
    currency: "IQD",
    remove: "Remove",
    noResults: "No results found",
    pieces: "pcs",
    lang: "English",
    iqd: "IQD",
  }
};

const CATEGORIES = [
  { id: "all", ar: "الكل", ku: "هەمووی", en: "All", icon: "🌿" },
  { id: "mostPopular", ar: "الاكثر شيوعاً", ku: "زۆرترین فرۆشراو", en: "Most Popular", icon: "⭐" },
  { id: "grills", ar: "المشويات", ku: "بریان", en: "Grills", icon: "🔥" },
  { id: "mandi", ar: "المندي", ku: "مەندی", en: "Mandi", icon: "🍚" },
  { id: "rawMaterials", ar: "المواد الخام", ku: "مادەی خاو", en: "Raw Materials", icon: "🌱" },
  { id: "rizzoSauces", ar: "صوصات الريزو", ku: "سۆسی ریزۆ", en: "Rizzo Sauces", icon: "🧄" },
  { id: "burgerSauces", ar: "صوصات البركر", ku: "سۆسی بەرگەر", en: "Burger Sauces", icon: "🍔" },
  { id: "selectedSauces", ar: "صوصات مختارة", ku: "سۆسی دیاریکراو", en: "Selected Sauces", icon: "✨" },
  { id: "westernKitchen", ar: "المطبخ الغربي", ku: "چێشتخانەی ڕۆژئاوا", en: "Western Kitchen", icon: "🥩" },
  { id: "easternKitchen", ar: "المطبخ الشرقي", ku: "چێشتخانەی ڕۆژهەڵات", en: "Eastern Kitchen", icon: "🫙" },
  { id: "italianKitchen", ar: "المطبخ الايطالي", ku: "چێشتخانەی ئیتاڵی", en: "Italian Kitchen", icon: "🍕" },
  { id: "fondue", ar: "الفنكر", ku: "فۆندیو", en: "Fondue", icon: "🧀" },
  { id: "dutchPepper", ar: "البقصم الهولندي", ku: "بیسکۆیتی هۆڵەندی", en: "Dutch Pepper", icon: "🫑" },
  { id: "flavors", ar: "النكهات", ku: "تامەکان", en: "Flavors", icon: "🌶️" },
  { id: "foodManufacturing", ar: "معامل المصنعات الغذائية", ku: "کارگەی خواردنی پیشەسازیکراو", en: "Food Manufacturing", icon: "🏭" },
];

const PRODUCTS = [
  // Most Popular
  { id: 1, category: "mostPopular", ar: "تخمير كنتاكي", ku: "تەخمیری کەنتاکی", en: "Kentucky Marinade", price: 15000, desc: { ar: "تتبيلة الدجاج الكنتاكي الأصيلة", ku: "تەخمیری مرۆشکی کەنتاکی ئەسڵ", en: "Authentic Kentucky chicken marinade" }, emoji: "🍗" },
  { id: 2, category: "mostPopular", ar: "قرمشة", ku: "قرمشە", en: "Crispy Coating", price: 15000, desc: { ar: "خلطة التقرمش المثالية", ku: "تێکەڵەی تاقمکردنی پاش", en: "Perfect crispy coating mix" }, emoji: "✨" },
  { id: 3, category: "mostPopular", ar: "زنجر", ku: "زنجەر", en: "Zinger", price: 15000, desc: { ar: "توابل الزنجر الحار", ku: "بهاراتی زنجەری تیژ", en: "Spicy zinger seasoning" }, emoji: "🌶️" },
  { id: 4, category: "mostPopular", ar: "كرسبي", ku: "کریسپی", en: "Crispy", price: 15000, desc: { ar: "توابل الكرسبي الذهبية", ku: "بهاراتی کریسپی زێڕین", en: "Golden crispy seasoning" }, emoji: "🌟" },

  // Grills
  { id: 5, category: "grills", ar: "كباب لحم", ku: "کەبابی گۆشت", en: "Meat Kebab", price: 15000, desc: { ar: "توابل الكباب العراقي الأصيل", ku: "بهاراتی کەبابی عێراقی ئەسڵ", en: "Authentic Iraqi kebab spices" }, emoji: "🍢" },
  { id: 6, category: "grills", ar: "كباب دجاج", ku: "کەبابی مرۆشک", en: "Chicken Kebab", price: 15000, desc: { ar: "توابل كباب الدجاج المميزة", ku: "بهاراتی کەبابی مرۆشکی تایبەت", en: "Special chicken kebab spices" }, emoji: "🍗" },
  { id: 7, category: "grills", ar: "شيش طاووق", ku: "شیش تاووق", en: "Shish Tawook", price: 15000, desc: { ar: "بهارات شيش طاووق الشهية", ku: "بهاراتی شیش تاووقی خۆشەویست", en: "Delicious shish tawook spices" }, emoji: "🍡" },
  { id: 8, category: "grills", ar: "دجاج مسحب", ku: "مرۆشکی کێشراو", en: "Pulled Chicken", price: 15000, desc: { ar: "توابل الدجاج المسحب الأمريكي", ku: "بهاراتی مرۆشکی کێشراوی ئەمریکی", en: "American pulled chicken spices" }, emoji: "🫙" },
  { id: 9, category: "grills", ar: "عرايس لحم", ku: "عرایسی گۆشت", en: "Meat Arayes", price: 15000, desc: { ar: "توابل عرايس اللحم اللبنانية", ku: "بهاراتی عرایسی گۆشتی لووبنانی", en: "Lebanese meat arayes spices" }, emoji: "🫓" },
  { id: 10, category: "grills", ar: "عرايس دجاج", ku: "عرایسی مرۆشک", en: "Chicken Arayes", price: 15000, desc: { ar: "توابل عرايس الدجاج اللبنانية", ku: "بهاراتی عرایسی مرۆشکی لووبنانی", en: "Lebanese chicken arayes spices" }, emoji: "🫓" },
  { id: 11, category: "grills", ar: "تكة لحم", ku: "تێکەی گۆشت", en: "Meat Tikka", price: 15000, desc: { ar: "توابل تكة اللحم الهندية", ku: "بهاراتی تێکەی گۆشتی هیندی", en: "Indian meat tikka spices" }, emoji: "🍖" },
  { id: 12, category: "grills", ar: "تكة دجاج", ku: "تێکەی مرۆشک", en: "Chicken Tikka", price: 15000, desc: { ar: "توابل تكة الدجاج الهندية", ku: "بهاراتی تێکەی مرۆشکی هیندی", en: "Indian chicken tikka spices" }, emoji: "🍗" },
  { id: 13, category: "grills", ar: "كباب هندي", ku: "کەبابی هیندی", en: "Indian Kebab", price: 15000, desc: { ar: "توابل الكباب الهندي الأصيل", ku: "بهاراتی کەبابی هیندی ئەسڵ", en: "Authentic Indian kebab" }, emoji: "🌿" },
  { id: 14, category: "grills", ar: "اجنحة مشوية", ku: "باڵی بریان", en: "Grilled Wings", price: 15000, desc: { ar: "توابل الاجنحة المشوية المميزة", ku: "بهاراتی باڵی بریانی تایبەت", en: "Special grilled wings spices" }, emoji: "🔥" },
  { id: 15, category: "grills", ar: "مسحب دجاج", ku: "مرۆشکی کێشراو", en: "Chicken Pulled", price: 15000, desc: { ar: "توابل الدجاج المسحب المثالية", ku: "بهاراتی مرۆشکی کێشراوی گونجاو", en: "Perfect pulled chicken spices" }, emoji: "🫙" },
  { id: 16, category: "grills", ar: "شاورما لحم", ku: "شاورما لحم", en: "Meat Shawarma", price: 15000, desc: { ar: "توابل شاورما لحم المثالية", ku: "بهارات شاورما لحم", en: "Perfect meat shawarma spices" }, emoji: "🦴" },
  { id: 17, category: "grills", ar: "شاورما دجاج", ku: "شاورما دجاج", en: "chicken shawarma", price: 15000, desc: { ar: "بهارات شاورما دجاج", ku: "بهارات شاورما دجاج", en: "chicken shawarma spices" }, emoji: "🍆" },

  // Mandi
  { id: 18, category: "mandi", ar: "مندي لحم", ku: "مەندی گۆشت", en: "Meat Mandi", price: 15000, desc: { ar: "توابل المندي اليمني الأصيل", ku: "بهاراتی مەندی یەمەنی ئەسڵ", en: "Authentic Yemeni meat mandi" }, emoji: "🍖" },
  { id: 19, category: "mandi", ar: "مندي دجاج", ku: "مەندی مرۆشک", en: "Chicken Mandi", price: 15000, desc: { ar: "توابل مندي الدجاج اليمني", ku: "بهاراتی مەندی مرۆشکی یەمەنی", en: "Yemeni chicken mandi spices" }, emoji: "🍗" },
  { id: 20, category: "mandi", ar: "تمن مندي", ku: "برنجی مەندی", en: "Mandi Rice", price: 15000, desc: { ar: "توابل رز المندي الفريدة", ku: "بهاراتی برنجی مەندی تایبەت", en: "Special mandi rice spices" }, emoji: "🍚" },
  { id: 21, category: "mandi", ar: "حنيذ لحم", ku: "حنیذی گۆشت", en: "Meat Haneeth", price: 15000, desc: { ar: "توابل الحنيذ اليمني التقليدي", ku: "بهاراتی حنیذی یەمەنی کلاسیکی", en: "Traditional Yemeni haneeth" }, emoji: "🫙" },
  { id: 22, category: "mandi", ar: "زربيان لحم", ku: "زربیانی گۆشت", en: "Meat Zarbyan", price: 15000, desc: { ar: "توابل الزربيان العريقة", ku: "بهاراتی زربیانی کەهن", en: "Ancient zarbyan spices" }, emoji: "🌿" },
  { id: 23, category: "mandi", ar: "مضبي لحم", ku: "مەضبی گۆشت", en: "Meat Madhbi", price: 15000, desc: { ar: "توابل المضبي الأصيلة", ku: "بهاراتی مەضبی ئەسڵ", en: "Authentic madhbi spices" }, emoji: "🔥" },
  { id: 24, category: "mandi", ar: "مضبي دجاج", ku: "مەضبی مرۆشک", en: "Chicken Madhbi", price: 15000, desc: { ar: "توابل مضبي الدجاج", ku: "بهاراتی مەضبی مرۆشک", en: "Chicken madhbi spices" }, emoji: "🍗" },

  // Raw Materials - Page 1
  { id: 25, category: "rawMaterials", ar: "فلفل حار", ku: "بیبەری تیژ", en: "Hot Pepper", price: null, desc: { ar: "فلفل حار طازج عالي الجودة", ku: "بیبەری تیژی تازەی بەرزکوالێتی", en: "High quality fresh hot pepper" }, emoji: "🌶️" },
  { id: 26, category: "rawMaterials", ar: "فلفل باكستاني", ku: "بیبەری پاکستانی", en: "Pakistani Pepper", price: null, desc: { ar: "فلفل باكستاني أصيل", ku: "بیبەری پاکستانی ئەسڵ", en: "Authentic Pakistani pepper" }, emoji: "🫑" },
  { id: 27, category: "rawMaterials", ar: "كمون", ku: "کیمون", en: "Cumin", price: null, desc: { ar: "كمون عربي عالي الجودة", ku: "کیمۆنی عەرەبی بەرزکوالێتی", en: "High quality Arabic cumin" }, emoji: "🌿" },
  { id: 28, category: "rawMaterials", ar: "شاي كجرات", ku: "چایی گوجرات", en: "Gujarat Tea", price: null, desc: { ar: "شاي كجرات الهندي الأصيل", ku: "چایی گوجراتی هیندی ئەسڵ", en: "Authentic Indian Gujarat tea" }, emoji: "🍃" },
  { id: 29, category: "rawMaterials", ar: "يانسون", ku: "یانسون", en: "Anise", price: null, desc: { ar: "يانسون طبيعي نقي", ku: "یانسۆنی سروشتی خالص", en: "Pure natural anise" }, emoji: "⭐" },
  { id: 30, category: "rawMaterials", ar: "ورد محمدي", ku: "گوڵی محمدی", en: "Damascus Rose", price: null, desc: { ar: "ورد محمدي طبيعي", ku: "گوڵی محمدی سروشتی", en: "Natural Damascus rose" }, emoji: "🌹" },
  { id: 31, category: "rawMaterials", ar: "ورد جوري", ku: "گوڵی جۆری", en: "Jouri Rose", price: null, desc: { ar: "ورد جوري عطري", ku: "گوڵی جۆری بۆنخۆش", en: "Fragrant Jouri rose" }, emoji: "🌸" },
  { id: 32, category: "rawMaterials", ar: "ورد محمدي", ku: "گوڵی محمدی", en: "Rose Petals", price: null, desc: { ar: "بتلات ورد محمدي", ku: "پەڕی گوڵی محمدی", en: "Damascus rose petals" }, emoji: "🌺" },
  { id: 33, category: "rawMaterials", ar: "ميرامية", ku: "میرامیا", en: "Sage", price: null, desc: { ar: "ميرامية طبيعية نقية", ku: "میرامیای سروشتی خالص", en: "Pure natural sage" }, emoji: "🌿" },
  { id: 34, category: "rawMaterials", ar: "اوريغانو", ku: "ئۆریگانۆ", en: "Oregano", price: null, desc: { ar: "اوريغانو إيطالي عالي الجودة", ku: "ئۆریگانۆی ئیتاڵی بەرزکوالێتی", en: "High quality Italian oregano" }, emoji: "🍃" },
  { id: 35, category: "rawMaterials", ar: "بذور الشيا", ku: "تۆی شیا", en: "Chia Seeds", price: null, desc: { ar: "بذور الشيا الغنية بالأوميغا", ku: "تۆی شیای دەوڵەمەند بە ئۆمیگا", en: "Omega-rich chia seeds" }, emoji: "⚫" },
  { id: 36, category: "rawMaterials", ar: "نعناع", ku: "نەمام", en: "Mint", price: null, desc: { ar: "نعناع طبيعي منعش", ku: "نەمامی سروشتی سووڕخۆش", en: "Fresh natural mint" }, emoji: "🌱" },
  { id: 37, category: "rawMaterials", ar: "حلبة", ku: "حلبە", en: "Fenugreek", price: null, desc: { ar: "حلبة طبيعية مطحونة", ku: "حلبەی سروشتی خڕاو", en: "Natural ground fenugreek" }, emoji: "🌿" },
  { id: 38, category: "rawMaterials", ar: "ليموندوزي", ku: "لیمووی دووزی", en: "Lemon Dozy", price: null, desc: { ar: "ليمون دوزي مجفف مطحون", ku: "لیمووی دووزی وشکی خڕاو", en: "Dried ground lemon dozy" }, emoji: "🍋" },
  { id: 39, category: "rawMaterials", ar: "صودا", ku: "سۆدا", en: "Baking Soda", price: null, desc: { ar: "بيكربونات الصوديوم النقية", ku: "بیکاربۆناتی سۆدیۆمی خالص", en: "Pure sodium bicarbonate" }, emoji: "⚪" },
  { id: 40, category: "rawMaterials", ar: "ورق غار", ku: "پەڕی گار", en: "Bay Leaves", price: null, desc: { ar: "ورق غار طبيعي مجفف", ku: "پەڕی گاری سروشتی وشکاو", en: "Natural dried bay leaves" }, emoji: "🍃" },
  { id: 41, category: "rawMaterials", ar: "حبة سوداء", ku: "تۆی ڕەش", en: "Black Seed", price: null, desc: { ar: "حبة البركة السوداء الأصيلة", ku: "تۆی بەرەکەی ڕەشی ئەسڵ", en: "Authentic black seed" }, emoji: "⚫" },
  { id: 42, category: "rawMaterials", ar: "بطنج", ku: "بطنج", en: "Mastic", price: null, desc: { ar: "بطنج طبيعي نقي", ku: "بطنجی سروشتی خالص", en: "Pure natural mastic" }, emoji: "💎" },
  { id: 43, category: "rawMaterials", ar: "كبابة", ku: "کبابە", en: "Cubeb", price: null, desc: { ar: "كبابة عطرية فريدة", ku: "کبابەی بۆنخۆشی تایبەت", en: "Unique fragrant cubeb" }, emoji: "🔴" },
  { id: 44, category: "rawMaterials", ar: "فلفل اسود", ku: "بیبەری ڕەش", en: "Black Pepper", price: null, desc: { ar: "فلفل أسود طازج مطحون", ku: "بیبەری ڕەشی تازەی خڕاو", en: "Fresh ground black pepper" }, emoji: "⚫" },
  // Page 2
  { id: 45, category: "rawMaterials", ar: "فلفل ابيض", ku: "بیبەری سپی", en: "White Pepper", price: null, desc: { ar: "فلفل أبيض نقي ناعم", ku: "بیبەری سپی خالصی نەرم", en: "Pure fine white pepper" }, emoji: "⚪" },
  { id: 46, category: "rawMaterials", ar: "كركم راجابوري", ku: "زەردچۆبەی راجابووری", en: "Rajabouri Turmeric", price: null, desc: { ar: "كركم راجابوري فاخر", ku: "زەردچۆبەی راجابووری نایاب", en: "Premium Rajabouri turmeric" }, emoji: "🟡" },
  { id: 47, category: "rawMaterials", ar: "دارسين مطحون", ku: "دارچینی خڕاو", en: "Ground Cinnamon", price: null, desc: { ar: "دارسين مطحون فاخر", ku: "دارچینی خڕاوی نایاب", en: "Premium ground cinnamon" }, emoji: "🟤" },
  { id: 48, category: "rawMaterials", ar: "دارسين ميكار", ku: "دارچینی میکار", en: "Mikar Cinnamon", price: null, desc: { ar: "دارسين ميكار اللبناني", ku: "دارچینی میکاری لووبنانی", en: "Lebanese Mikar cinnamon" }, emoji: "🌿" },
  { id: 49, category: "rawMaterials", ar: "دارسين بوري", ku: "دارچینی بووری", en: "Bouri Cinnamon", price: null, desc: { ar: "دارسين بوري طبيعي", ku: "دارچینی بووری سروشتی", en: "Natural Bouri cinnamon" }, emoji: "🍃" },
  { id: 50, category: "rawMaterials", ar: "هيل مطحون", ku: "هێل خڕاو", en: "Ground Cardamom", price: null, desc: { ar: "هيل مطحون عالي الجودة", ku: "هێلی خڕاوی بەرزکوالێتی", en: "High quality ground cardamom" }, emoji: "💚" },
  { id: 51, category: "rawMaterials", ar: "بصل مطحون", ku: "پیازی خڕاو", en: "Onion Powder", price: null, desc: { ar: "بصل مجفف مطحون", ku: "پیازی وشکاوی خڕاو", en: "Dried ground onion" }, emoji: "🧅" },
  { id: 52, category: "rawMaterials", ar: "بصل شرائح", ku: "پیازی بڕاو", en: "Sliced Onion", price: null, desc: { ar: "شرائح بصل مجففة", ku: "پیازی بڕاوی وشکاو", en: "Dried sliced onion" }, emoji: "🧅" },
  { id: 53, category: "rawMaterials", ar: "ثوم مطحون عادي", ku: "سەریمی خڕاوی ئاساری", en: "Regular Garlic Powder", price: null, desc: { ar: "ثوم مطحون طبيعي", ku: "سەریمی خڕاوی سروشتی", en: "Natural garlic powder" }, emoji: "🧄" },
  { id: 54, category: "rawMaterials", ar: "ثوم مطحون امريكي", ku: "سەریمی خڕاوی ئەمریکی", en: "American Garlic Powder", price: null, desc: { ar: "ثوم مطحون أمريكي فاخر", ku: "سەریمی خڕاوی ئەمریکی نایاب", en: "Premium American garlic powder" }, emoji: "🧄" },
  { id: 55, category: "rawMaterials", ar: "ثوم شرائح", ku: "سەریمی بڕاو", en: "Sliced Garlic", price: null, desc: { ar: "شرائح ثوم مجففة", ku: "سەریمی بڕاوی وشکاو", en: "Dried sliced garlic" }, emoji: "🧄" },
  { id: 56, category: "rawMaterials", ar: "كزبرة", ku: "گەشنیج", en: "Coriander", price: null, desc: { ar: "كزبرة مطحونة فاخرة", ku: "گەشنیجی خڕاوی نایاب", en: "Premium ground coriander" }, emoji: "🌿" },
  { id: 57, category: "rawMaterials", ar: "زنجبيل", ku: "زەنجەفیل", en: "Ginger", price: null, desc: { ar: "زنجبيل طبيعي عطري", ku: "زەنجەفیلی سروشتی بۆنخۆش", en: "Natural aromatic ginger" }, emoji: "🫚" },
  { id: 58, category: "rawMaterials", ar: "حبة حلوة", ku: "تۆی شیرین", en: "Sweet Seeds", price: null, desc: { ar: "حبة حلوة طبيعية", ku: "تۆی شیرینی سروشتی", en: "Natural sweet seeds" }, emoji: "🟡" },
  { id: 59, category: "rawMaterials", ar: "جوزة الطيب", ku: "جۆزەی ناسرین", en: "Nutmeg", price: null, desc: { ar: "جوزة الطيب الكاملة", ku: "جۆزەی ناسرینی تەواو", en: "Whole nutmeg" }, emoji: "🟤" },
  { id: 60, category: "rawMaterials", ar: "قرنفل", ku: "قازیایەک", en: "Cloves", price: null, desc: { ar: "قرنفل كامل عطري", ku: "قازیایەکی تەواوی بۆنخۆش", en: "Fragrant whole cloves" }, emoji: "🔴" },
  { id: 61, category: "rawMaterials", ar: "روزماري", ku: "ڕۆزماری", en: "Rosemary", price: null, desc: { ar: "روزماري طبيعي منعش", ku: "ڕۆزماریی سروشتی سووڕخۆش", en: "Fresh natural rosemary" }, emoji: "🌿" },
  { id: 62, category: "rawMaterials", ar: "زعتر", ku: "زەتەر", en: "Thyme", price: null, desc: { ar: "زعتر طبيعي أصيل", ku: "زەتەری سروشتی ئەسڵ", en: "Authentic natural thyme" }, emoji: "🍃" },
  { id: 63, category: "rawMaterials", ar: "بابريكا بودر", ku: "پاپریکای پووڕی", en: "Paprika Powder", price: null, desc: { ar: "بابريكا مطحونة ناعمة", ku: "پاپریکای خڕاوی نەرم", en: "Fine ground paprika" }, emoji: "🔴" },
  { id: 64, category: "rawMaterials", ar: "بابريكا خشنة", ku: "پاپریکای قرژ", en: "Coarse Paprika", price: null, desc: { ar: "بابريكا خشنة للتتبيل", ku: "پاپریکای قرژی بۆ تەخمیر", en: "Coarse paprika for marinating" }, emoji: "🫑" },
  // Page 3
  { id: 65, category: "rawMaterials", ar: "بابريكا مدخنة", ku: "پاپریکای دووکەڵاو", en: "Smoked Paprika", price: null, desc: { ar: "بابريكا مدخنة فاخرة", ku: "پاپریکای دووکەڵاوی نایاب", en: "Premium smoked paprika" }, emoji: "💨" },
  { id: 66, category: "rawMaterials", ar: "سماك", ku: "سماق", en: "Sumac", price: null, desc: { ar: "سماك طازج حامض", ku: "سماقی تازەی تریش", en: "Fresh sour sumac" }, emoji: "🔴" },
  { id: 67, category: "rawMaterials", ar: "نومي بصرة", ku: "نوومی بەسرە", en: "Basra Lime", price: null, desc: { ar: "نومي بصرة مجفف أصيل", ku: "نوومی بەسرەی وشکاوی ئەسڵ", en: "Authentic dried Basra lime" }, emoji: "🍋" },

  // Rizzo Sauces
  { id: 68, category: "rizzoSauces", ar: "ريزو كلاسك", ku: "ریزۆی کلاسیک", en: "Classic Rizzo", price: 12000, desc: { ar: "صوص الريزو الكلاسيكي الأصيل", ku: "سۆسی ریزۆی کلاسیکی ئەسڵ", en: "Authentic classic Rizzo sauce" }, emoji: "🧄" },
  { id: 69, category: "rizzoSauces", ar: "ريزو اعشاب", ku: "ریزۆی گیایی", en: "Herb Rizzo", price: 12000, desc: { ar: "صوص الريزو بالأعشاب الطبيعية", ku: "سۆسی ریزۆی گیایی سروشتی", en: "Natural herb Rizzo sauce" }, emoji: "🌿" },
  { id: 70, category: "rizzoSauces", ar: "ريزو بالجبنة", ku: "ریزۆی پنیری", en: "Cheese Rizzo", price: 12000, desc: { ar: "صوص الريزو بالجبنة الكريمية", ku: "سۆسی ریزۆی پنیری کرێمی", en: "Creamy cheese Rizzo sauce" }, emoji: "🧀" },
  { id: 71, category: "rizzoSauces", ar: "ريزو سبايسي", ku: "ریزۆی تیژ", en: "Spicy Rizzo", price: 12000, desc: { ar: "صوص الريزو الحار المميز", ku: "سۆسی ریزۆی تیژی تایبەت", en: "Special spicy Rizzo sauce" }, emoji: "🌶️" },
  { id: 72, category: "rizzoSauces", ar: "ريزو مدخن", ku: "ریزۆی دووکەڵاو", en: "Smoked Rizzo", price: 12000, desc: { ar: "صوص الريزو المدخن الشهي", ku: "سۆسی ریزۆی دووکەڵاوی خۆشەویست", en: "Delicious smoked Rizzo sauce" }, emoji: "💨" },

  // Burger Sauces
  { id: 73, category: "burgerSauces", ar: "برغر كلاسك", ku: "بەرگەری کلاسیک", en: "Classic Burger Sauce", price: 15000, desc: { ar: "صوص البرغر الكلاسيكي الأصيل", ku: "سۆسی بەرگەری کلاسیکی ئەسڵ", en: "Authentic classic burger sauce" }, emoji: "🍔" },
  { id: 74, category: "burgerSauces", ar: "برغر اعشاب", ku: "بەرگەری گیایی", en: "Herb Burger Sauce", price: 15000, desc: { ar: "صوص البرغر بالأعشاب", ku: "سۆسی بەرگەری گیایی", en: "Herb burger sauce" }, emoji: "🌿" },
  { id: 75, category: "burgerSauces", ar: "برغر سبايس", ku: "بەرگەری تیژ", en: "Spicy Burger Sauce", price: 15000, desc: { ar: "صوص البرغر الحار", ku: "سۆسی بەرگەری تیژ", en: "Spicy burger sauce" }, emoji: "🌶️" },
  { id: 76, category: "burgerSauces", ar: "برغر بالجبنة", ku: "بەرگەری پنیری", en: "Cheese Burger Sauce", price: 15000, desc: { ar: "صوص البرغر بالجبنة", ku: "سۆسی بەرگەری پنیری", en: "Cheese burger sauce" }, emoji: "🧀" },

  // Selected Sauces
  { id: 77, category: "selectedSauces", ar: "صوص المتحدة", ku: "سۆسی یەکگرتوو", en: "United Sauce", price: 12000, desc: { ar: "الصوص الحصري للشركة المتحدة", ku: "سۆسی تایبەتی کۆمپانیای یەکگرتوو", en: "Exclusive United Company sauce" }, emoji: "⭐" },
  { id: 78, category: "selectedSauces", ar: "صوص اوريجنال", ku: "سۆسی ئۆریجینال", en: "Original Sauce", price: 12000, desc: { ar: "الصوص الأصلي المميز", ku: "سۆسی ئەسڵی تایبەت", en: "Distinctive original sauce" }, emoji: "✨" },
  { id: 79, category: "selectedSauces", ar: "صوص الديدهوت", ku: "سۆسی دیدهۆت", en: "Deadhot Sauce", price: 12000, desc: { ar: "صوص الديدهوت الحار جداً", ku: "سۆسی دیدهۆتی زۆر تیژ", en: "Very spicy Deadhot sauce" }, emoji: "🔥" },

  // Western Kitchen
  { id: 80, category: "westernKitchen", ar: "ستيك لحم", ku: "ستیکی گۆشت", en: "Meat Steak", price: 15000, desc: { ar: "توابل الستيك الاحترافية", ku: "بهاراتی ستیکی پیشەکار", en: "Professional steak spices" }, emoji: "🥩" },
  { id: 81, category: "westernKitchen", ar: "ستيك دجاج", ku: "ستیکی مرۆشک", en: "Chicken Steak", price: 15000, desc: { ar: "توابل ستيك الدجاج", ku: "بهاراتی ستیکی مرۆشک", en: "Chicken steak spices" }, emoji: "🍗" },
  { id: 82, category: "westernKitchen", ar: "سكالوب لحم", ku: "ئیسکالۆپی گۆشت", en: "Meat Scallop", price: 15000, desc: { ar: "توابل سكالوب اللحم", ku: "بهاراتی ئیسکالۆپی گۆشت", en: "Meat scallop spices" }, emoji: "🥩" },
  { id: 83, category: "westernKitchen", ar: "سكالوب دجاج", ku: "ئیسکالۆپی مرۆشک", en: "Chicken Scallop", price: 15000, desc: { ar: "توابل سكالوب الدجاج", ku: "بهاراتی ئیسکالۆپی مرۆشک", en: "Chicken scallop spices" }, emoji: "🍗" },
  { id: 84, category: "westernKitchen", ar: "فاهيتا لحم", ku: "فاهیتای گۆشت", en: "Meat Fajita", price: 15000, desc: { ar: "توابل فاهيتا اللحم المكسيكية", ku: "بهاراتی فاهیتای گۆشتی مەکسیکی", en: "Mexican meat fajita spices" }, emoji: "🌮" },
  { id: 85, category: "westernKitchen", ar: "فاهيتا دجاج", ku: "فاهیتای مرۆشک", en: "Chicken Fajita", price: 15000, desc: { ar: "توابل فاهيتا الدجاج المكسيكية", ku: "بهاراتی فاهیتای مرۆشکی مەکسیکی", en: "Mexican chicken fajita spices" }, emoji: "🌮" },
  { id: 86, category: "westernKitchen", ar: "كوردن بلو", ku: "کۆردۆن بلۆ", en: "Cordon Bleu", price: 15000, desc: { ar: "توابل الكوردن بلو الفرنسي", ku: "بهاراتی کۆردۆن بلۆی فەرەنسی", en: "French Cordon Bleu spices" }, emoji: "🧀" },
  { id: 87, category: "westernKitchen", ar: "ستيك دجاج باربيكيو", ku: "ستیکی مرۆشکی باربیکیو", en: "BBQ Chicken Steak", price: 15000, desc: { ar: "ستيك الدجاج بالباربيكيو", ku: "ستیکی مرۆشکی باربیکیو", en: "BBQ chicken steak" }, emoji: "🔥" },
  { id: 88, category: "westernKitchen", ar: "فيلادلفيا لحم", ku: "فیلادیلفیای گۆشت", en: "Philly Meat", price: 14000, desc: { ar: "توابل فيلادلفيا ستيك اللحم", ku: "بهاراتی فیلادیلفیا ستیکی گۆشت", en: "Philly steak meat spices" }, emoji: "🥪" },
  { id: 89, category: "westernKitchen", ar: "فيلادلفيا دجاج", ku: "فیلادیلفیای مرۆشک", en: "Philly Chicken", price: 15000, desc: { ar: "توابل فيلادلفيا ستيك الدجاج", ku: "بهاراتی فیلادیلفیا ستیکی مرۆشک", en: "Philly steak chicken spices" }, emoji: "🥪" },

  // Eastern Kitchen
  { id: 90, category: "easternKitchen", ar: "برياني لحم", ku: "بریانی گۆشت", en: "Meat Biryani", price: 15000, desc: { ar: "توابل البرياني الهندي الأصيل", ku: "بهاراتی بریانی هیندی ئەسڵ", en: "Authentic Indian biryani" }, emoji: "🍚" },
  { id: 91, category: "easternKitchen", ar: "برياني دجاج", ku: "بریانی مرۆشک", en: "Chicken Biryani", price: 15000, desc: { ar: "توابل برياني الدجاج", ku: "بهاراتی بریانی مرۆشک", en: "Chicken biryani spices" }, emoji: "🍗" },
  { id: 92, category: "easternKitchen", ar: "دولمة", ku: "دۆلمە", en: "Dolma", price: 15000, desc: { ar: "توابل الدولمة العراقية الأصيلة", ku: "بهاراتی دۆڵمەی عێراقی ئەسڵ", en: "Authentic Iraqi dolma" }, emoji: "🫑" },
  { id: 93, category: "easternKitchen", ar: "كبسة لحم", ku: "کبسەی گۆشت", en: "Meat Kabsa", price: 15000, desc: { ar: "توابل الكبسة السعودية الأصيلة", ku: "بهاراتی کبسەی سعوودی ئەسڵ", en: "Authentic Saudi kabsa" }, emoji: "🍖" },
  { id: 94, category: "easternKitchen", ar: "كبسة دجاج", ku: "کبسەی مرۆشک", en: "Chicken Kabsa", price: 15000, desc: { ar: "توابل كبسة الدجاج السعودية", ku: "بهاراتی کبسەی مرۆشکی سعوودی", en: "Saudi chicken kabsa" }, emoji: "🍗" },
  { id: 95, category: "easternKitchen", ar: "مقلوبة لحم", ku: "مەقلووبەی گۆشت", en: "Meat Maqluba", price: 15000, desc: { ar: "توابل المقلوبة الفلسطينية", ku: "بهاراتی مەقلووبەی فەلەستینی", en: "Palestinian maqluba spices" }, emoji: "🍚" },
  { id: 96, category: "easternKitchen", ar: "مقلوبة دجاج", ku: "مەقلووبەی مرۆشک", en: "Chicken Maqluba", price: 15000, desc: { ar: "توابل مقلوبة الدجاج الفلسطينية", ku: "بهاراتی مەقلووبەی مرۆشکی فەلەستینی", en: "Palestinian chicken maqluba" }, emoji: "🍗" },
  { id: 97, category: "easternKitchen", ar: "دجاج مشوي", ku: "مرۆشکی بریان", en: "Grilled Chicken", price: 15000, desc: { ar: "توابل الدجاج المشوي الشرقي", ku: "بهاراتی مرۆشکی بریانی ڕۆژهەڵاتی", en: "Eastern grilled chicken" }, emoji: "🔥" },
  { id: 98, category: "easternKitchen", ar: "كاري", ku: "کاری", en: "Curry", price: 14000, desc: { ar: "كاري هندي أصيل", ku: "کاریی هیندی ئەسڵ", en: "Authentic Indian curry" }, emoji: "🍛" },
  { id: 99, category: "easternKitchen", ar: "تشريب لحم", ku: "تەشریبی گۆشت", en: "Meat Tashreeb", price: 15000, desc: { ar: "توابل تشريب اللحم العراقي", ku: "بهاراتی تەشریبی گۆشتی عێراقی", en: "Iraqi meat tashreeb" }, emoji: "🍲" },
  { id: 100, category: "easternKitchen", ar: "تشريب دجاج", ku: "تەشریبی مرۆشک", en: "Chicken Tashreeb", price: 15000, desc: { ar: "توابل تشريب الدجاج العراقي", ku: "بهاراتی تەشریبی مرۆشکی عێراقی", en: "Iraqi chicken tashreeb" }, emoji: "🍲" },
  { id: 101, category: "easternKitchen", ar: "قوزي", ku: "قووزی", en: "Ghouzi", price: 15000, desc: { ar: "توابل القوزي العراقي الأصيل", ku: "بهاراتی قووزی عێراقی ئەسڵ", en: "Authentic Iraqi ghouzi" }, emoji: "🐑" },
  { id: 102, category: "easternKitchen", ar: "جدر", ku: "جادەر", en: "Jader", price: 15000, desc: { ar: "توابل الجدر العراقي التقليدي", ku: "بهاراتی جادەری عێراقی کلاسیکی", en: "Traditional Iraqi jader" }, emoji: "🫙" },
  { id: 103, category: "easternKitchen", ar: "فلافل", ku: "فلافل", en: "Falafel", price: 15000, desc: { ar: "توابل الفلافل العربية الأصيلة", ku: "بهاراتی فلافلی عەرەبی ئەسڵ", en: "Authentic Arabic falafel" }, emoji: "🧆" },
  { id: 104, category: "easternKitchen", ar: "قيمة", ku: "قیمە", en: "Qeema", price: 14000, desc: { ar: "توابل القيمة اللحمية", ku: "بهاراتی قیمەی گۆشت", en: "Meat qeema spices" }, emoji: "🫙" },
  { id: 105, category: "easternKitchen", ar: "بهارات السبعة", ku: "بهاراتی حەوت", en: "Seven Spices", price: 15000, desc: { ar: "خلطة البهارات السبعة الشامية", ku: "تێکەڵەی بهاراتی حەوتی شامی", en: "Levantine seven spice blend" }, emoji: "🌟" },
  { id: 106, category: "easternKitchen", ar: "كاري هندي", ku: "کاریی هیندی", en: "Indian Curry", price: 14000, desc: { ar: "كاري هندي فاخر", ku: "کاریی هیندی نایاب", en: "Premium Indian curry" }, emoji: "🍛" },
  { id: 107, category: "easternKitchen", ar: "سمك", ku: "ماسی", en: "Fish", price: 15000, desc: { ar: "توابل السمك المميزة", ku: "بهاراتی ماسی تایبەت", en: "Special fish spices" }, emoji: "🐟" },

  // Italian Kitchen
  { id: 108, category: "italianKitchen", ar: "بيتزا لحم", ku: "پیتزای گۆشت", en: "Meat Pizza", price: 15000, desc: { ar: "توابل بيتزا اللحم الإيطالية", ku: "بهاراتی پیتزای گۆشتی ئیتاڵی", en: "Italian meat pizza spices" }, emoji: "🍕" },
  { id: 109, category: "italianKitchen", ar: "بيتزا دجاج", ku: "پیتزای مرۆشک", en: "Chicken Pizza", price: 15000, desc: { ar: "توابل بيتزا الدجاج الإيطالية", ku: "بهاراتی پیتزای مرۆشکی ئیتاڵی", en: "Italian chicken pizza spices" }, emoji: "🍕" },
  { id: 110, category: "italianKitchen", ar: "بيتزا خضار", ku: "پیتزای سەوزە", en: "Veggie Pizza", price: 15000, desc: { ar: "توابل بيتزا الخضار", ku: "بهاراتی پیتزای سەوزە", en: "Vegetable pizza spices" }, emoji: "🥗" },
  { id: 111, category: "italianKitchen", ar: "لحم بعجين ", ku: "لحمبعجين", en: "lahmacun", price: 15000, desc: { ar: "بهارات لحم بعجين", ku: "بهارات لحم بعجين", en: "lahmacun spices" }, emoji: "🍝" },
  { id: 112, category: "italianKitchen", ar: "فوتوشيني دجاج", ku: "لحم بعجين", en: "Chicken Fettuccine", price: 15000, desc: { ar: "صوص الفوتوشيني بالكريمة والدجاج", ku: "سۆسی فۆتووچینیی کرێمی و مرۆشک", en: "Creamy chicken fettuccine" }, emoji: "🍝" },
  { id: 113, category: "italianKitchen", ar: "لزانيا لحم", ku: "لازانیای گۆشت", en: "Meat Lasagna", price: 15000, desc: { ar: "توابل لزانيا اللحم الإيطالية", ku: "بهاراتی لازانیای گۆشتی ئیتاڵی", en: "Italian meat lasagna spices" }, emoji: "🫙" },
  { id: 114, category: "italianKitchen", ar: "لزانيا دجاج", ku: "لازانیای مرۆشک", en: "Chicken Lasagna", price: 15000, desc: { ar: "توابل لزانيا الدجاج الإيطالية", ku: "بهاراتی لازانیای مرۆشکی ئیتاڵی", en: "Italian chicken lasagna" }, emoji: "🫙" },

  // Fondue
  { id: 115, category: "fondue", ar: "فنكر كلاسك", ku: "فۆندیووی کلاسیک", en: "Classic Fondue", price: 12000, desc: { ar: "خلطة الفنكر الكلاسيكية", ku: "تێکەڵەی فۆندیووی کلاسیک", en: "Classic fondue blend" }, emoji: "🧀" },
  { id: 116, category: "fondue", ar: "فنكر بالجبن", ku: "فۆندیووی پنیری", en: "Cheese Fondue", price: 12000, desc: { ar: "فنكر الجبن الكريمي", ku: "فۆندیووی پنیری کرێمی", en: "Creamy cheese fondue" }, emoji: "🫕" },
  { id: 117, category: "fondue", ar: "فنكر بالاعشاب", ku: "فۆندیووی گیایی", en: "Herb Fondue", price: 12000, desc: { ar: "فنكر الأعشاب الطبيعية", ku: "فۆندیووی گیایی سروشتی", en: "Natural herb fondue" }, emoji: "🌿" },
  { id: 118, category: "fondue", ar: "فنكر مدخن", ku: "فۆندیووی دووکەڵاو", en: "Smoked Fondue", price: 12000, desc: { ar: "فنكر مدخن فاخر", ku: "فۆندیووی دووکەڵاوی نایاب", en: "Premium smoked fondue" }, emoji: "💨" },

  // Dutch Pepper
  { id: 119, category: "dutchPepper", ar: "بقصم برتقالي", ku: "بیسکۆیتی پرتەقاڵی", en: "Orange Rusks", price: 4000, desc: { ar: "بقصم برتقالي هولندي طازج", ku: "بیسکۆیتی پرتەقاڵی هۆڵەندی تازە", en: "Fresh Dutch orange rusks" }, emoji: "🍊" },
  { id: 120, category: "dutchPepper", ar: "بقصم اصفر", ku: "بیسکۆیتی زەرد", en: "Yellow Rusks", price: 4000, desc: { ar: "بقصم أصفر هولندي كلاسيكي", ku: "بیسکۆیتی زەردی هۆڵەندی کلاسیک", en: "Classic Dutch yellow rusks" }, emoji: "⭐" },

  // Flavors
  { id: 121, category: "flavors", ar: "جبنة الشيدر", ku: "پنیری چیدار", en: "Cheddar Cheese", price: 10000, desc: { ar: "نكهة الجبن الشيدر الأصيلة", ku: "تامی پنیری چیداری ئەسڵ", en: "Authentic cheddar cheese flavor" }, emoji: "🧀" },
  { id: 122, category: "flavors", ar: "جبنة فرنسية", ku: "پنیری فەرەنسی", en: "French Cheese", price: 9000, desc: { ar: "نكهة الجبن الفرنسي الفاخر", ku: "تامی پنیری فەرەنسی نایاب", en: "Premium French cheese flavor" }, emoji: "🧀" },
  { id: 123, category: "flavors", ar: "ماجي دجاج", ku: "ماگی مرۆشک", en: "Chicken Maggi", price: 8000, desc: { ar: "نكهة ماجي الدجاج المميزة", ku: "تامی ماگی مرۆشکی تایبەت", en: "Special chicken maggi flavor" }, emoji: "🍗" },
  { id: 124, category: "flavors", ar: "ماجي لحم", ku: "ماگی گۆشت", en: "Meat Maggi", price: 8000, desc: { ar: "نكهة ماجي اللحم المميزة", ku: "تامی ماگی گۆشتی تایبەت", en: "Special meat maggi flavor" }, emoji: "🥩" },
  { id: 125, category: "flavors", ar: "نكهة الدخان", ku: "تامی دوکان", en: "Smoke Flavor", price: 9000, desc: { ar: "نكهة الدخان الأصيلة", ku: "تامی دووکەڵی ئەسڵ", en: "Authentic smoke flavor" }, emoji: "💨" },
  { id: 126, category: "flavors", ar: "نكهة الخل و الملح", ku: "تامی سرکە و خوێ", en: "Vinegar & Salt", price: 8000, desc: { ar: "نكهة الخل والملح الكلاسيكية", ku: "تامی سرکە و خوێی کلاسیک", en: "Classic vinegar and salt flavor" }, emoji: "🧂" },
  { id: 127, category: "flavors", ar: "اللبن بالاعشاب", ku: "ماستی گیایی", en: "Herb Yogurt", price: 8000, desc: { ar: "نكهة اللبن بالأعشاب الطازجة", ku: "تامی ماستی گیایی تازە", en: "Fresh herb yogurt flavor" }, emoji: "🌿" },
  { id: 128, category: "flavors", ar: "سبايسي", ku: "تیژ", en: "Spicy", price: 9000, desc: { ar: "نكهة الحار المميزة", ku: "تامی تیژی تایبەت", en: "Special spicy flavor" }, emoji: "🌶️" },

  // Food Manufacturing
  { id: 129, category: "foodManufacturing", ar: "كبة موصلية", ku: "کوبەی مووسڵ", en: "Mosuli Kubba", price: null, desc: { ar: "مزيج كبة موصلية أصيلة", ku: "تێکەڵەی کوبەی مووسڵی ئەسڵ", en: "Authentic Mosuli kubba mix" }, emoji: "🫙" },
  { id: 130, category: "foodManufacturing", ar: "كبة حلب", ku: "کوبەی حەلەب", en: "Aleppo Kubba", price: null, desc: { ar: "مزيج كبة حلب الشامي", ku: "تێکەڵەی کوبەی حەلەبی شامی", en: "Levantine Aleppo kubba" }, emoji: "🫙" },
  { id: 131, category: "foodManufacturing", ar: "كبة السراي", ku: "کوبەی سەرای", en: "Saray Kubba", price: null, desc: { ar: "مزيج كبة السراي المميزة", ku: "تێکەڵەی کوبەی سەرایی تایبەت", en: "Special Saray kubba" }, emoji: "🫙" },
  { id: 132, category: "foodManufacturing", ar: "برغر لحم", ku: "بەرگەری گۆشت", en: "Meat Burger", price: null, desc: { ar: "خلطة البرغر اللحمي المصنعة", ku: "تێکەڵەی بەرگەری گۆشتی پیشەسازیکراو", en: "Processed meat burger mix" }, emoji: "🍔" },
  { id: 133, category: "foodManufacturing", ar: "برغر دجاج", ku: "بەرگەری مرۆشک", en: "Chicken Burger", price: null, desc: { ar: "خلطة البرغر الدجاجي المصنعة", ku: "تێکەڵەی بەرگەری مرۆشکی پیشەسازیکراو", en: "Processed chicken burger mix" }, emoji: "🍔" },
  { id: 134, category: "foodManufacturing", ar: "سكالوب لحم", ku: "ئیسکالۆپی گۆشت", en: "Meat Scalop", price: null, desc: { ar: "خلطة سكالوب اللحم المصنعة", ku: "تێکەڵەی ئیسکالۆپی گۆشتی پیشەسازیکراو", en: "Processed meat scalop" }, emoji: "🥩" },
  { id: 135, category: "foodManufacturing", ar: "سكالوب دجاج", ku: "ئیسکالۆپی مرۆشک", en: "Chicken Scalop", price: null, desc: { ar: "خلطة سكالوب الدجاج المصنعة", ku: "تێکەڵەی ئیسکالۆپی مرۆشکی پیشەسازیکراو", en: "Processed chicken scalop" }, emoji: "🍗" },
  { id: 136, category: "foodManufacturing", ar: "كياب لحم", ku: "کیابی گۆشت", en: "Meat Kiyab", price: null, desc: { ar: "خلطة كياب اللحم", ku: "تێکەڵەی کیابی گۆشت", en: "Meat kiyab mix" }, emoji: "🫙" },
  { id: 137, category: "foodManufacturing", ar: "باسطرمة", ku: "باستوورما", en: "Pastrami", price: null, desc: { ar: "خلطة الباسطرمة المميزة", ku: "تێکەڵەی باستوورمای تایبەت", en: "Special pastrami mix" }, emoji: "🥩" },
  { id: 138, category: "foodManufacturing", ar: "بنيتة جاب", ku: "بنیتەی جاب", en: "Banita Jab", price: null, desc: { ar: "خلطة بنيتة جاب", ku: "تێکەڵەی بنیتەی جاب", en: "Banita Jab mix" }, emoji: "🌿" },
  { id: 139, category: "foodManufacturing", ar: "ناكيت", ku: "ناکیت", en: "Nuggets", price: null, desc: { ar: "خلطة ناكيت الدجاج", ku: "تێکەڵەی ناکیتی مرۆشک", en: "Chicken nuggets mix" }, emoji: "🍗" },
];
